option('audio_backend', type : 'combo', choices : ['none', 'sdl', 'jack', 'wasapi'], value : 'sdl')
option('midi_backend', type : 'combo', choices : ['none', 'alsa', 'mmeapi'], value : 'none')
option('boost_stacktrace', type : 'feature', value : 'auto')
option('tracy', type : 'feature', value: 'disabled')
