[build-system]
build-backend = "mesonpy"
requires = [
    "meson",
    "meson-python",
    "ninja",
    "pybind11"
]

[project]
name = "mollytime"
version = "0.0"
license-files = [ "LICENSE.txt" ]
readme = "README.md"
dependencies = [
    "pygame"
]

[tool.meson-python.args]
install = [ "--tags=package" ]