[build-system]
build-backend = "mesonpy"
requires = [
    "meson",
    "meson-python",
    "ninja"
]

[project]
name = "mollytime"
version = "0.0"
license-files = [ "LICENSE.txt" ]
readme = "README.md"
dependencies = []

[tool.meson-python]
allow-windows-internal-shared-libs = true

[tool.meson-python.args]
install = [ "--tags=package" ]